version: '3.2'

services:
  nginx:
    image: nginx:1.19.2-alpine
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./www:/var/www
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/nginx/locations.conf:/etc/nginx/locations.conf
      - ./etc/nginx/ssl_redirect.conf:/etc/nginx/ssl_redirect.conf
      - ./etc/nginx/cert.conf:/etc/nginx/cert.conf
      - ./etc/nginx/cmc_com.conf:/etc/nginx/cmc_com.conf
      - ./etc/nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./etc/nginx/tools-enabled:/etc/nginx/tools-enabled
      - ./etc/nginx/ssl:/etc/nginx/ssl
      - ./log/nginx_log:/var/log/nginx
    depends_on:
      - php

  php:
    build: ./builder/php
    container_name: php
    volumes:
      - ./www:/var/www
      - ./etc/php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - 8000:8000
    links:
      - db
      - redis
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal remote_port=9000 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"

  composer:
    image: "composer"
    container_name: composer
    volumes:
      - ./www:/app
    command: bash -c "cd /app/catmodecode.tk && composer install"
    depends_on:
      - php

  db:
    image: postgres:12-alpine
    container_name: db
    restart: always
    env_file:
      - ".env"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data/db:/var/lib/postgresql/data

  dbadmin:
    image: dpage/pgadmin4:4.28
    container_name: dbadmin
    env_file:
      - ".env"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_ENABLE_TLS: ${PGADMIN_ENABLE_TLS}
    volumes:
      - ./etc/nginx-selfsigned.crt:/certs/server.cert
      - ./etc/nginx-selfsigned.key:/certs/server.key
    
  redis:
    image: redis:6.0.6
    container_name: redis
    restart: always
    volumes:
      - ./data/redisdb:/data

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "8081:8081"

  rabbitmq:
    build: ./builder/rabbitmq
    container_name: rabbitmq
    env_file:
      - ".env"
    ports:
      - "${RABBITMQ_NODE_HOST_PORT}:5672"
    privileged: true
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    restart: always
    depends_on:
      - php

  mail:
    container_name: mail
    restart: unless-stopped
    image: eaudeweb/mailtrap
    ports:
      - "8125:80"
      - "2525:25"
    environment:
      - MT_USER=${MT_USER}
      - MT_PASSWD=${MT_PASSWD}
      - MT_MAILBOX_LIMIT=${MT_MAILBOX_LIMIT}
      - MT_MESSAGE_LIMIT=${MT_MESSAGE_LIMIT}

  cron:
    container_name: cron
    privileged: true
    restart: unless-stopped
    build: ./builder/cron
    volumes:
      - "./data/cron/crontab/root.cron:/var/spool/cron/crontabs/root"
      - "./data/cron/scripts:/cronscripts"
      - "//var/run/docker.sock:/var/run/docker.sock"
